version: '3.1'

services:
  user_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./db_init/user.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5482:5432

  object_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./db_init/data.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5483:5432

  clickhouse:
    image: clickhouse/clickhouse-server
    environment:
      CLICKHOUSE_DB: reactions
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: alphabet
    ports:
      - 18423:8123
      - 19400:9000

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  auth_service:
    build:
      dockerfile: ./AuthService/Dockerfile
      context: .
    depends_on:
      - user_db
      - object_service
      - kafka
    environment:
      DATABASE_HOST: user_db
      DATABASE_NAME: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      DATA_SERVICE_ADDRESS: "object_service:8295"
    ports:
      - 8095:8080

  object_service:
    build:
      dockerfile: ./DataService/Dockerfile
      context: .
    environment:
      DATABASE_HOST: object_db
      DATABASE_NAME: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_PORT: 5432
      HOST: ''
      PORT: 8295
    ports:
      - 8195:8295

  stat_service:
    build:
      dockerfile: ./StatService/Dockerfile
      context: .
    depends_on:
      - auth_service
      - clickhouse
      - kafka
    ports:
      - 8295:8080