@startuml
!include <C4/C4_Context>

Person(user, "Пользователь")

System(list, "Страница со списком задач")
System(task, "Страница задачи")

Rel(user, list, "Получает список задач, примененяет фильтры")
Rel(user, task, "Получает информацию о задаче: информация, лайки, комментарии, статистика")
@enduml