@startuml
!include <C4/C4_Context>

Person(user, "Пользователь")

System(main, "Главная страница")
System(stats, "Статистика")
System(data, "Данные о задачах, комментариях и тд")

Rel(user, main, "Отвечает на все запросы: аутентификация, создание задач, прожатие лайков, фильтрация, получение списка задач")
Rel(main, data, "Получает сырую информацию о задачах, комментариях и прочих объектах")
Rel(main, stats, "Получает статистику об объектах")
@enduml